// React/Normal/AngularVsReact/src/Components/Common/Navbar.jsx
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';

class Navbar extends PureComponent {
  render() {
    const { showNewTodo } = this.props;

    return (
      <nav className="navbar navbar-dark bg-dark">
        <span className="navbar-brand mb-0 h1">Todo app</span>
        <button type="button" className="btn btn-success" onClick={showNewTodo}>Add todo list</button>
      </nav>
    );
  }
}

Navbar.propTypes = {
  showNewTodo: PropTypes.func.isRequired,
};

Navbar.defaultProps = {
};

export default Navbar;

// Angular/Normal/AngularVsReact/src/app/layout/nav-bar/nav-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoService } from 'src/app/services/todo.service';

@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.scss']
})
export class NavBarComponent implements OnInit {
  constructor(public todoService: TodoService) {}

  ngOnInit() {}

  public addTodo() {
    this.todoService.showNewTodoBlock = true;
  }
}

<nav class="navbar navbar-dark bg-dark">
  <span class="navbar-brand mb-0 h1">Todo app</span>
  <div class="btn btn-success" (click)="addTodo()">Add todo list</div>
</nav>
